import { DataHeaders } from "../Datasets/DatasetTypes";

export enum SearchType {
    DisplayNone,
    Checkbox,
    TextSearch,
  }

  export const searchTitles: Record<DataHeaders, SearchType> = {
    Index: SearchType.DisplayNone,
    "Citation Key": SearchType.DisplayNone,
    "Paper Name": SearchType.DisplayNone,
    Authors: SearchType.TextSearch,
    Year: SearchType.TextSearch,
    Journal: SearchType.TextSearch,
    "Journal ISO Abbreviation": SearchType.TextSearch,
    Title: SearchType.TextSearch,
    Abstract: SearchType.TextSearch,
    DOI: SearchType.TextSearch,
    ISSN: SearchType.DisplayNone,
    url: SearchType.DisplayNone,
    "Open Access": SearchType.DisplayNone,
    "Reviewer 1": SearchType.DisplayNone,
    "Reviewer 2": SearchType.DisplayNone,
    Scope: SearchType.Checkbox,
    "Eco-Evo Focus": SearchType.Checkbox,
    Metric: SearchType.DisplayNone,
    "Life history": SearchType.Checkbox,
    "Ecological Loci/Traits": SearchType.Checkbox,
    "Additional Loci/Traits": SearchType.DisplayNone,
    "Mating system": SearchType.Checkbox,
    Ploidy: SearchType.Checkbox,
    Selection: SearchType.Checkbox,
    "Spatial Structure": SearchType.Checkbox,
    "Population Size": SearchType.Checkbox,
    "Ecological Model": SearchType.Checkbox,
    "Recurrent Mutation": SearchType.Checkbox,
    IBS: SearchType.Checkbox,
  };

  //for checkbox search types, record their options
  export const searchCheckBoxOptions: Record<string, string[]> = {
    Scope: [
      "Single Model",
      "Multi Model",
      "Not a MS Model",
      "Review",
      "Meta-analysis",
      "Data Analysis",
      "PDF Not Available",
      "Other",
    ],
    "Eco-Evo Focus": [
      "Variation (Divergence)",
      "Pop. Persistance and Conservation",
      "Coevolution",
      "Range Dynamic",
      "Evol. Processes",
      "Repeatability",
      "Other",
      "Unknown",
      "NA",
    ],
    "Life history": ["Discrete", "Continous", "Unknown"],
    "Ecological Loci/Traits": [
      "1 Locus/2 allele",
      "2 Loci",
      "Multi_locus(>2 loci)",
      "Multi-allelic",
      "1 trait",
      "Multi-traits",
      "NA",
      "Other",
      "Unknown",
    ],
    "Mating system": [
      "Asex",
      "Hermaphrodite",
      "Diecious",
      "Dimorphic",
      "Self-fertilization",
      "Unknown",
      "NA",
    ],
    Ploidy: ["Haploid", "Diploid", "Haplodiploid", "Other", "Unknown", "NA"],
    Selection: [
      "Gaussian/Quad Stab",
      "GFG",
      "MAM",
      "Pheno Diff/Pheno Match",
      "Other",
      "Unknown",
    ],
    "Spatial Structure": [
      "2-patch",
      "Metapopulation (Finite or Infinite)",
      "Island Mainland",
      "Stepping Stone(1D,2D)",
      "Continous Space (1D or 2D)",
      "Other",
      "Unknown",
    ],
    "Population Size": ["Finite", "Infinite", "Both", "Other"],
    "Ecological Model": [
      "Constant",
      "Stochastic",
      "Intraspecific Competition",
      "Interspecific Competition",
      "Epidemiological",
      "Other",
      "Unknown",
    ],
    "Recurrent Mutation": [
      "Yes",
      "No",
      "Other",
      "Adaptive Dynamics",
      "Unknown",
    ],
    IBS: ["IBS", "Analytical Model", "Both", "Unknown"],
  };
